image: python:3-alpine

before_script:
  - apk update
  - apk add zip

stages:
  - test
  - build

test:
  stage: test
  script:
    - python -mjson.tool 'cs-CZ/cs.json' > /dev/null
    - python -mjson.tool 'cs-CZ/module.json' > /dev/null

build:
  stage: build
  script:
    - zip cs-CZ.zip -r cs-CZ -x ".*"
  artifacts:
    name: cs-CZ
    when: on_success
    paths:
      - cs-CZ.zip
  when: on_success
  only:
    - tags
    - master
